config/routes.rb
Rails.application.routes.draw do
  

  resources :users

  resources :projects do #, :only => [] do 
    resources :posts
    resources :pledges
  end

  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  
  
  root  :to => "application#index"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/pledge.rb
class Pledge < ActiveRecord::Base
  belongs_to :user
  belongs_to :project  
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :project
  has_many :comments
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  has_many :posts
  has_many :pledges
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  has_secure_password
  has_many :projects
  has_many :comments
  has_many :pledges
 
  
  
  after_destroy :ensure_an_admin_remains

  private
    def ensure_an_admin_remains
      if User.count.zero?
        raise "Can't delete last user"
      end
    end       
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  def index
    
    render '/index'
  end
end

app/controllers/pledges_controller.rb
class PledgesController < ApplicationController
  
 before_action :prepare_project
 
  def create
    @pledge = @project.pledges.build(posts_params)
    @pledge.user_id = params[:user_id]    
    if @pledge.save
      redirect_to @project, :notice => "pldege added successfully"
    end
  end

  def index
    @pledges = @project.pledges
  end

  def destroy
    @pledge.destroy
  end
  
  private
   
  def prepare_project
    @project = Project.find(params[:project_id])
    @pledge = @project.pledges.find(params[:id]) if params[:id]
  end
    
  def posts_params
    params.require(:pledge).permit(:desc, :amount)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  before_action :prepare_project
 
  def create
    @post = @project.posts.build(posts_params)
    @post.user_id = params[:user_id]    
    if @post.save
      redirect_to @project, :notice => "posted successfully"
    end
  end

  def index
    @posts = @project.posts
  end

  def destroy
    @post.destroy
  end
  
  private
   
  def prepare_project
    @project = Project.find(params[:project_id])
    @post = @project.posts.find(params[:id]) if params[:id]
  end
    
  def posts_params
    params.require(:post).permit(:content, :published)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  def index
    @projects = Project.all
  end

  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, :budget, :published, :closed, :target_date, :category, :description)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

   def create
    user = User.find_by(name: params[:name])
    if user and user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to projects_path
    else
      redirect_to login_url, alert: "Invalid user/password"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Logged out"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :password, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pledge_helper.rb
module PledgeHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<div id="footer">
      <div class="container">
        <center>This is powered by User </center>
      </div>
</div>

app/views/layouts/_header.html.erb
 <div class="pull-right">
    <% if session[:user_id] %>
     <%= link_to "Logout", logout_path, method: :delete, class:"btn btn-info" %>
     <% else %>
   <%= link_to "Login", login_path, class:"btn btn-info" %>
   <% end %>
  </div>
<div class="page-header">
  <h1> Kick Start </h1>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>KickStarter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <%= yield %>
  </div>
  <%= render 'layouts/footer' %>
</body>
</html>

app/views/pledges/_form.html.erb
<%- @pledge ||= @project.pledges.build %>
<%= form_for([@project,@pledge]) do | f| %>
  <% if @pledge.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pledge.errors.count, "error") %> prohibited this pledge from being saved:</h2>
<ul>
        <% @pledge.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
      
    </div>
  <% end %>
 <div class="field">
    <%= f.label :amount %><br>
   <%= f.text_field :amount %>
  </div>

  <div class="field">
    <%= f.label :desc %><br>
    <%= f.text_area :desc %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  

<% end %>

app/views/pledges/create.html.erb
<h1>Pledge#create</h1>
<p>Find me in app/views/pledge/create.html.erb</p>

app/views/pledges/destroy.html.erb
<h1>Pledge#destroy</h1>
<p>Find me in app/views/pledge/destroy.html.erb</p>

app/views/pledges/index.html.erb
<h1>Pledge#index</h1>
<p>Find me in app/views/pledge/index.html.erb</p>

app/views/pledges/new.html.erb
<h1>Pledge#new</h1>
<p>Find me in app/views/pledge/new.html.erb</p>

app/views/posts/_form.html.erb
<%- @post ||= @project.posts.build %>
<%= form_for([@project,@post]) do | f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
<ul>
        <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
      
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <div class="span9">
    <%= f.text_area :content,  rows: 6, cols:50, class:"span6" %>
    </div>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  

<% end %>

app/views/posts/destroy.html.erb
<h1>Post#destroy</h1>
<p>Find me in app/views/post/destroy.html.erb</p>

app/views/posts/index.html.erb
<h1>Post#index</h1>
<p>Find me in app/views/post/index.html.erb</p>

app/views/posts/new.html.erb
<h1>Post#new</h1>
<p>Find me in app/views/post/new.html.erb</p>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :budget %><br>
    <%= f.text_field :budget %>
  </div>
  <div class="field">
    <%= f.label :published %><br>
    <%= f.check_box :published %>
  </div>
  <div class="field">
    <%= f.label :closed %><br>
    <%= f.check_box :closed %>
  </div>
  <div class="field">
    <%= f.label :target_date %><br>
    <%= f.date_select :target_date %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>Listing projects</h1>

<table class="table table-bordered  table-hover">
  <thead>
    <tr>
      <th class="col-md-2">Title</th>
      <th class="col-md-2">Budget</th>
      <th class="col-md-2" >Published</th>
      <th class="col-md-2">Closed</th>
      <th class="col-md-2">Target date</th>
      <th class="col-md-2">Category</th>
      <th class="col-md-2">Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.title %></td>
        <td><%= project.budget %></td>
        <td><%= project.published %></td>
        <td><%= project.closed %></td>
        <td><%= project.target_date %></td>
        <td><%= project.category %></td>
        <td><%= project.description %></td>
        <td><%= link_to 'Show', project, class: "btn btn-info btn-sm" %></td>
        <td><%= link_to 'Edit', edit_project_path(project), class: "btn btn-success btn-sm" %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @project.title %>
</p>

<p>
  <strong>Budget:</strong>
  <%= @project.budget %>
</p>

<p>
  <strong>Published:</strong>
  <%= @project.published %>
</p>

<p>
  <strong>Closed:</strong>
  <%= @project.closed %>
</p>

<p>
  <strong>Target date:</strong>
  <%= @project.target_date %>
</p>

<p>
  <strong>Category:</strong>
  <%= @project.category %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>
<hr/>
<div class="row">
  <div class="col-xs-12 col-sm-6">
    <h4>Project Post </h4>
  <div class="well">
    <% if @project.posts.count > 0 %>
    <ul id="posts">
  <% @project.posts.each do | p |  %>
  <li> <%= p.content %>
  <% end %>
  </ul>
  <% end %>
  </div>
    <%= render '/posts/form' %> 
</div>
  <div class="col-xs-12 col-sm-6">
    <h4>Project Pledge </h4>
   <div class="well">    
    <ul id="pledges">
      <% @project.pledges.each do | pl |  %>
      <li> <b><%= pl.amount %> </b>  <%=pl.desc %>
        <% end %>
      </ul>
     <%= render '/pledges/form' %>
  </div>
  </div>
</div>
<hr/>


<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>



<div class="modal fade" id="new_person_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
<!-- link_to 'New Person', '#new_person_modal', 'data-toggle' => 'modal' -->
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Create new person</h4>
      </div>
      <div class="modal-body">
        <%# Render the new person form (passing modal => true to enable remote => true) %>
  <%= render '/pledges/form', modal: true %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/users/_form.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
  User Sign Up
  </div>
   <div class="panel-body">
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
   
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
     
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>

  <div class="field">
     <%= f.label :password_confirmation, 'Confirm:' %> <br>
    <%= f.password_field :password_confirmation%>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
  </div>
   <div class="panel-footer">
  </div>
</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table class="table-border table-hover">
  <thead>
    <tr>
      <th class="col-md-2">Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user, class: "btn btn-info btn-sm" %></td>
        <td><%= link_to 'Edit', edit_user_path(user),  class: "btn btn-success btn-sm" %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>